import type { Prompt } from './types';

export const prompts: Prompt[] = [
// Casual — weighted toward taking a position, not describing a thing.
// A prompt with a thesis is what makes timeToFirstPoint and bloatRatio mean anything.
{ text: "Explain something you're good at to someone who's never tried it", category: 'casual' },
{ text: "Talk about something you changed your mind about recently", category: 'casual' },
{ text: "Describe the best piece of advice you've ever been given, and why it stuck", category: 'casual' },
{ text: "Explain a popular opinion you think is wrong", category: 'casual' },
{ text: "Make the case for a hobby you think more people should try", category: 'casual' },
{ text: "Argue for the most underrated place you've been", category: 'casual' },
{ text: "Convince someone to read a book or watch a film you love", category: 'casual' },
{ text: "Explain why a piece of advice everyone repeats is actually bad", category: 'casual' },
{ text: "Make the case for doing absolutely nothing on a day off", category: 'casual' },
{ text: "Explain what people most often get wrong about your field or hobby", category: 'casual' },
{ text: "Describe a skill you think everyone should learn, and why", category: 'casual' },
{ text: "Make the case for a rule you'd change if you could", category: 'casual' },
{ text: "Explain a piece of technology you think we'd be better off without", category: 'casual' },
{ text: "Argue for the best way to spend a free hour", category: 'casual' },
{ text: "Explain something you used to believe and no longer do", category: 'casual' },
{ text: "Explain what makes something worth paying extra for", category: 'casual' },
{ text: "Describe a decision you'd make differently if you could go back", category: 'casual' },
{ text: "Argue for the most useful thing you learned outside a classroom", category: 'casual' },
{ text: "Explain why someone should or shouldn't move to where you live", category: 'casual' },
{ text: "Make the case against a trend you think is overrated", category: 'casual' },
{ text: "Explain what you think is the most overused phrase right now", category: 'casual' },
{ text: "Describe what you'd want to be known for in ten years", category: 'casual' },
{ text: "Argue for the best way to learn something new from scratch", category: 'casual' },
{ text: "Explain a small thing that improves your day more than it should", category: 'casual' },
{ text: "Make the case for finishing something you're not enjoying", category: 'casual' },
{ text: "Explain why you think people procrastinate, and what actually helps", category: 'casual' },
{ text: "Describe one change you'd make to how school works", category: 'casual' },
{ text: "Explain what you look for in a good conversation", category: 'casual' },
{ text: "Argue for a meal you could happily eat every day", category: 'casual' },

// Behavioural — the standard competency areas interviewers actually hire against:
// leadership, teamwork, problem-solving, communication/conflict, adaptability, time management.
{ text: "Describe a time you overcame a challenge", category: 'behavioural' },
{ text: "Tell me about a time you worked in a group and things didn't go smoothly", category: 'behavioural' },
{ text: "Describe a project you're proud of and your role in it", category: 'behavioural' },
{ text: "Tell me about a time you had to learn something new quickly", category: 'behavioural' },
{ text: "Describe a time you disagreed with someone and how you handled it", category: 'behavioural' },
{ text: "Tell me about a time you made a mistake and what you did next", category: 'behavioural' },
{ text: "Describe a time you had to manage several deadlines at once", category: 'behavioural' },
{ text: "Tell me about a goal you set for yourself and how you pursued it", category: 'behavioural' },
{ text: "Describe a time you helped someone who was struggling", category: 'behavioural' },
{ text: "Tell me about a time you had to adapt when plans changed", category: 'behavioural' },
{ text: "Describe a time you took initiative without being asked", category: 'behavioural' },
{ text: "Tell me about a time you received feedback and what you did with it", category: 'behavioural' },
{ text: "Tell me about a time you led a team through a difficult project", category: 'behavioural' },
{ text: "Describe a time you had to make an unpopular decision", category: 'behavioural' },
{ text: "Tell me about a time you motivated someone who had lost interest", category: 'behavioural' },
{ text: "Describe a time you had to lead people who didn't report to you", category: 'behavioural' },
{ text: "Tell me about a time you worked with someone difficult", category: 'behavioural' },
{ text: "Describe a time you had to compromise to reach a group decision", category: 'behavioural' },
{ text: "Tell me about a time you covered for a teammate who wasn't delivering", category: 'behavioural' },
{ text: "Describe a time your team failed and what you took from it", category: 'behavioural' },
{ text: "Tell me about a time you spotted a problem before anyone else did", category: 'behavioural' },
{ text: "Describe a decision you had to make without all the information", category: 'behavioural' },
{ text: "Tell me about a time your first solution didn't work", category: 'behavioural' },
{ text: "Describe a creative solution you came up with under tight constraints", category: 'behavioural' },
{ text: "Tell me about a time you persuaded someone to change their mind", category: 'behavioural' },
{ text: "Describe a time you had to give someone difficult feedback", category: 'behavioural' },
{ text: "Tell me about a time you explained something complex to a non-expert", category: 'behavioural' },
{ text: "Describe a time a miscommunication caused a problem and how you fixed it", category: 'behavioural' },
{ text: "Tell me about a time you had to say no or push back on a request", category: 'behavioural' },
{ text: "Describe a time you missed a deadline and what happened next", category: 'behavioural' },
{ text: "Tell me about a time you worked under real pressure", category: 'behavioural' },
{ text: "Describe a time you went beyond what was asked of you", category: 'behavioural' }]
